### ISSUE TITLE
Send IR codes from internal IR emitter in the remote

### ISSUE THREAD

**Issue by martonborzak** [unfoldedcircle/feature-and-bug-tracker#75]
At the moment we can only send IR commands through the dock. However, the remote has an IR emitter as well, but software support hasn't been implemented yet.

The internal IR emitter allows sending IR commands immediately after wakeup and doesn't require network connectivity.

## Features

- [x] Proof of concept: send PRONTO codes with the internal IR emitter
- [x] Convert learned codes from the dock to raw timings (dock and remote use different hardware for sending IR codes).
      This conversion function will also be available as API endpoint.

First release: v1.5.1 published in BETA group
- [x] Send PRONTO codes and learned codes from the dock with the internal IR emitter
- [x] Make internal IR emitter available as selectable output device in web-configurator

Second release:
- [x] Native IR repeat for supported IR protocols.  
      Depending on IR protocol, pressing & holding a button will send a different IR code. Certain devices require this for example for a smooth or progressive volume change.

**Comment by zehnm** [comment]
Current status: POC is working and feature should be ready before mid-December.

**Comment by zehnm** [comment]
The first release has been published to the BETA group as a preview feature (firmware v1.5.1). If we don’t find any showstoppers, it will be released to the public within the next one or two days.

### Limitations in v1.5.1

Our initial focus was on PRONTO codes and converting the learned IR codes from the dock. Because of the different hardware for sending IR in the dock and the remote, the learned codes have to be converted. There's a chance that certain protocols might not yet work, due to invalid conversions.

Please be aware that IR protocol specific IR-code repeat is not yet supported. We also have to fix an issue in the UI, which sends too many IR commands when a button is hold. This can lead to "runaway IR commands" when the button is released: the device still receives the command multiple times for a few seconds.

‼️ **Please be careful using volume commands with the internal IR blaster until native IR-repeat is available**!
_Update:_ This is only for the internal IR blaster in the remote. The dock is not affected and uses ir-repeat with a stop signal when the button is released, plus a safety mechanism in the dock itself in case the network connection drops.

### How to enable the internal IR blaster

- In the web-configurator, open the Settings menu and scroll down to the Development section:
<img width="866" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/7eea209e-601c-4d86-861f-a99ec8674080">

- Enable the `Internal infrared (IR) blaster` feature:

<img width="565" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/66676b55-9567-4fbb-b9b1-35bfada52b27">

- The remote must be restarted for the feature to be activated.
  Perform a reboot either directly in the preview dialog, or with the physical power button on the remote.

**Comment by zehnm** [comment]
Available as preview feature in v1.5.2.
IR repeat is still missing and will be implemented in an update.

**Comment by d22b** [comment]
Can confirm that this feature is working. But here is the same issue as with the internal IR in the dock. It to weak to pass 6-7M direct line of sight. Shorter distances are no problem.

That’s really a pitty.

**Comment by spamoni4** [comment]
I tested the IR Emitter from the Remote, I had to be about 4.5 feet from the IR Receiver in order for it to be seen and control the TV.  I have a 77" TV and sit approximately 13.4 feet from the TV and the remote could not control the TV.  I have the same issue with the base, so I had to put the base on my mantle to get it to work.

In addition, it appears that you need to be in direct Line of site for it to function correctly.  Being off to the side yielded no control of the TV

**Comment by d22b** [comment]
Yes, it is actually crap.

**Comment by jliebl-git** [comment]
The emitter in the remote is working fine enough for me, the main issue is that I specifically have to select either the remote or the dock.
I can see that having both simultaneously is not the greatest of Ideas due to latencies and resulting duplicate inputs.
At least during times where there is no connection to the Dock it would be great to have the Remote IR emitter as a fallback. For example directly after picking up to at least power on a TV.

Maybe related to #295 #262 #249 and probably some more

**Comment by HandoffBarry** [comment]
> The emitter in the remote is working fine enough for me, the main issue is that I specifically have to select either the remote or the dock. I can see that having both simultaneously is not the greatest of Ideas due to latencies and resulting duplicate inputs. At least during times where there is no connection to the Dock it would be great to have the Remote IR emitter as a fallback. For example directly after picking up to at least power on a TV.
> 
> Maybe related to #295 #262 #249 and probably some more

Are you not able to set specific devices to use specific IR emitters? I see the main use case for this being the ability to control devices inside of a cabinet or another room with the dock while also being able to control IR devices that are sitting right in front of you (similar to the Harmony).

**Comment by WillTriumph1** [comment]
See 1 Feb comment.  It would be great if it worked reliably when picking up remote, but waving it around for the red bar to go away is less than satisfying with a correctly working dock.  It would be a feature that the IR emitter would work until the dock emitters are “live” and functioning.

**Comment by HandoffBarry** [comment]
> See 1 Feb comment. It would be great if it worked reliably when picking up remote, but waving it around for the red bar to go away is less than satisfying with a correctly working dock. It would be a feature that the IR emitter would work until the dock emitters are “live” and functioning.



> See 1 Feb comment. It would be great if it worked reliably when picking up remote, but waving it around for the red bar to go away is less than satisfying with a correctly working dock. It would be a feature that the IR emitter would work until the dock emitters are “live” and functioning.

Yeah I get that. I just find it curious that you can only select one emitter or the other (remote or dock). Is that the case across all devices or is that for each device in your setup?

**Comment by z-master42** [comment]
After activation in the preview functions and restarting the remote control, the internal IR emitter does not appear in the IR port selection. Am I missing something?

**Comment by RolandFran** [comment]
I have LED candles in different rooms. I can't reliably turn them on and off using the Dock. With the Remote 3, I should be able to control the candles more selectively and reliably. Unfortunately, the built-in IR emitter doesn't work at all for me. What am I doing wrong?

**Comment by kennymc-c** [comment]
Do you have it enabled under settings/development/preview features and select it as the output device in the entitiy?

**Comment by RolandFran** [comment]
Aah, found it - Its working now thanks!

**Comment by zehnm** [comment]
Native IR repeat for supported IR protocols has been released in beta version 2.9.13

**Comment by zehnm** [comment]
Every item on the list is done: the internal emitter has been selectable as an output device since v1.5.2, and native IR repeat for the supported protocols shipped in beta 2.9.13. Closing this tracking issue as completed.
